artifacts_root: artifacts    # All outputs files saved in artifacts folder

data_ingestion: 
 root_dir: artifacts/data_ingestion                                                                                 # main folder for data ingestion 
 source_url: https://github.com/mayurkadam9833/Datasets/raw/refs/heads/main/mental_health_social_media_dataset.zip  # url for download data file
 local_data_path: artifacts/data_ingestion/mental_health_social_media_dataset.zip                                   # download data path file
 unzip_dir: artifacts/data_ingestion                                                                                # unzip data file path

data_validation: 
 root_dir: artifacts/data_validation                                           # main folder for data validation
 unzip_data: artifacts/data_ingestion/mental_health_social_media_dataset.csv   # extracted data path
 status: artifacts/data_validation/validation_status.txt                       # schema validation text file

data_transformation: 
 root_dir: artifacts/data_transformation                                       # main folder for data transformation                                                                                          
 data_path: artifacts/data_ingestion/mental_health_social_media_dataset.csv    # extracted data path

model_trainer: 
 root_dir: artifacts/model_trainer                                             # main folder for model trainer 
 train_data: artifacts/data_transformation/train_data.csv                      # train data path

model_evaluation: 
 root_dir: artifacts/model_evaluation                                          # main folder for model evaluation
 test_data: artifacts/data_transformation/test_data.csv                        # test data path for evaluation
 model_path: artifacts/model_trainer/model.joblib                              # trained model path
 evaluation: artifacts/model_evaluation/metrics.json                           # classification metrics file
